modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/pietro-lopes/AllTheLeaks/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"
logoFile = "icon.png"

[[dependencies.alltheleaks]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.alltheleaks]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.alltheleaks]]
modId = "geckolib"
mandatory = false
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${geckolib_version_range}"
reason = "Update mod above to include latest memory leak fixes!"
ordering = "NONE"
side = "BOTH"

[[dependencies.alltheleaks]]
modId = "moonlight"
mandatory = false
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${moonlight_version_range}"
reason = "Update mod above to include latest memory leak fixes!"
ordering = "NONE"
side = "BOTH"